export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MunicipalitiesLayout({ children }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
