import "./globals.css";
import SupabaseListener from "@/components/supabaseListener";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="Ja">
      <body>
        <div>
          <SupabaseListener />
        </div>
        {children}
      </body>
    </html>
  );
}
